name: modrinth
description: A CLI wrapper for the Modrinth API
version: 0.0.4
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


publish_to: none

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  build_runner: ^2.1.8
  console: ^4.1.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  logging: ^1.0.2
  modrinth_api: 
    path: ../modrinth_api
  path: ^1.8.2
